lzc-sdk-version: "0.1"
name: GodoOS
package: cloud.lazycat.app.godoos
version: 0.0.2
description: 一款高效的内网办公操作系统
homepage: https://godoos.com/home/os/
author: godoos
application:
  subdomain: godoos
  background_task: true
  public_path:
    - /
  routes:
    - /=http://godoos:56780/
services:
  godoos:
    image: registry.lazycat.cloud/czyt/godoos/godoos:c4254f42dc2a663e
    binds:
      - /lzcapp/var/os:/root/.godoos/os

locales:
  zh:
    name: "GodoOS"
    description: "一款高效的内网办公操作系统"
  zh_CN:
    name: "GodoOS"
    description: "一款高效的内网办公操作系统"
  en:
    name: "GodoOS"
    description: "A self-hostable operating system for office work"
